version: '3.3'

# Docker Compose file for Docker Swarm deployment

networks:
  internal:
    driver: overlay
  traefik-net:
    external: true

volumes:
  mongo:
  storage:

services:
  mongo:
    image: mongo
    networks:
      - internal
    volumes:
      - mongo:/data/db

  app:
    image: briansostudio/release-center:latest
    volumes:
      - storage:/usr/src/app/storage
    ports:
      - "3000"
    networks:
      - internal
      - traefik-net
    deploy:
      labels:
        traefik.frontned.rule: Host:release.brianso.space
        traefik.port: 3000
        traefik.docker.network: traefik-net
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo/release_center
